-- Veranstaltung 24988 structured content JSON
-- Generated: 2026-06-23
-- Applies the reviewed _iss_content_json document imported from the Gutenberg event format sheet.
-- Public rendering remains on the legacy Veranstaltung body until the renderer switch is explicitly implemented.

START TRANSACTION;

DELETE FROM wp_postmeta
WHERE post_id = 24988
  AND meta_key = '_iss_content_json';

INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES
(24988, '_iss_content_json', '{\"schema_version\":1,\"entity_key\":\"event.vortrag\",\"sections\":[{\"type\":\"intro\",\"body\":\"14. Oktober 2025 | 19 Uhr | Industriesalon Schöneweide\\nNew York, Rio – Schöneweide? Dieses Salongespräch fragte nach neuen Wohngebieten, globalen Vergleichen und der Zukunft eines Stadtteils, in dem eines der größten Industriedenkmäler Deutschlands steht.\\nZu Gast waren David Weiblein (BTB), Wyatt Gordon (Stadtplaner und Journalist) und Annette Berfelde (Stadtentwicklungsamt, vorbereitende Stadtplanung). Moderiert wurde der Abend von Jana Birthelmer.\\nIm Mittelpunkt standen Fragen nach städtebaulicher Attraktivität, neuen Nachbarschaften, Investitionsdynamik und den Spielräumen einer sozialen, denkmalbewussten Entwicklung in Schöneweide.\"},{\"type\":\"kapitel\",\"kicker\":\"Thema\",\"title\":\"Worum geht es?\",\"body\":\"Kurze Einordnung des Abends. Der Vortrag setzt ein klares Thema, erklärt den Bezug zum Ort und macht verständlich, warum dieser Termin jetzt relevant ist.\",\"media_refs\":[{\"kind\":\"media\",\"source\":\"wp-media\",\"id\":\"26558\",\"label\":\"Bild2_Kraftwerk\",\"width\":\"800\",\"height\":\"578\"}]},{\"type\":\"kapitel\",\"kicker\":\"Ablauf\",\"body\":\"18:00 - Einlass - Ankommen und Orientierung\\n18:30 - Vortrag - Impuls mit Bildern, Quellen oder Material\\n19:30 - Gespräch - Fragen und Austausch\"},{\"type\":\"kapitel\",\"kicker\":\"Referent:in\",\"title\":\"Name und Perspektive\",\"body\":\"Kurzer Absatz zur Person, Rolle, Expertise und zum Bezug des Beitrags zum Thema.\"},{\"type\":\"kapitel\",\"kicker\":\"Kontext\",\"title\":\"Warum dieser Abend?\",\"body\":\"Hier steht der Zusammenhang mit Schöneweide, dem Industriesalon, einer Ausstellung, einem Projekt oder einer aktuellen Debatte.\",\"media_refs\":[{\"kind\":\"media\",\"source\":\"wp-media\",\"id\":\"26428\",\"label\":\"image2\",\"width\":\"830\",\"height\":\"912\"}]},{\"type\":\"material\",\"kicker\":\"Materialien\",\"title\":\"Downloads und Quellen\",\"items\":[\"PDF - Vortragsfolien, Handout oder Manuskript - Download\",\"Link - Weiterführende Quelle, Projektseite oder Literaturhinweis - extern\"],\"media_refs\":[{\"kind\":\"media\",\"source\":\"wp-media\",\"id\":\"26428\",\"label\":\"image2\",\"width\":\"830\",\"height\":\"912\"}],\"object_refs\":[{\"kind\":\"archive_object\",\"source\":\"iss-archive\",\"id\":\"15127\",\"label\":\"Informationstext über das NEF auf kyrillisch. Die Übersetzung lautet: In dem auf dem Gelände des Werkes FAO AEG gelegenen Büro, das sich in…\",\"thumbnail\":\"http://192.168.2.31:8082/wp-content/uploads/2026/05/Album_NEF_Seite_03-150x150.jpg\",\"set_id\":\"19\",\"member_id\":\"4469\",\"set_title\":\"NEF-Album\"}]}]}');

COMMIT;
